//
// Autogenerated by Thrift Compiler (0.17.0)
//
// DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
//
import thrift = require('thrift');
import Thrift = thrift.Thrift;
import Q = thrift.Q;
import Int64 = require('node-int64');


declare class Position {
    public x: number;
    public y: number;

      constructor(args?: { x: number; y: number; });
  }

declare class Firefly {
    public position: Position;
    public phase: number;

      constructor(args?: { position: Position; phase: number; });
  }
